# Generated by Django 3.2.5 on 2021-07-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210726_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('cover', models.ImageField(default='default_cover.png', upload_to='covers')),
            ],
        ),
    ]
