# Generated by Django 3.2.5 on 2021-07-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20),
        ),
    ]
