# Generated by Django 3.2.5 on 2021-07-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210726_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('identity', models.CharField(max_length=50, unique=True)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
