# Generated by Django 3.2.5 on 2021-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
