# Generated by Django 3.2.5 on 2021-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
    ]
